### ISSUE TITLE
Basemap Image and simulation slow

### ISSUE THREAD

**Issue by JesusLopezBaeza** [CityScope/CSL_Hamburg_HPA#11]
Hi @agrignard,
-We're trying to add a Google satellite image as a backgroud, but the feature 'GoogleMaps Image Import' in Gama Library Models seems to be not working with the current API. Could we get some help with that? We also tried importing a regular png/tif/jpg image but it gets resized and we can't geo-reference it correctly.
-We're currently workin in the model HBF_Detail. The simulation starts running slow with more than 10 'tourist' agents. Could you please help us optimize that to be able to work with more?

**Comment by agrignard** [comment]
Hi @JesusLopezBaeza in general any issue that seems related directly to GAMA can be reported here by documenting how to reproduce it. Don't forget to specify the version of GAMA you are  using, the OS you are running and the part of the code or the feature that you think is not working.

Here is the issue link
https://github.com/gama-platform/gama/issues

For the second issue of course it shouldn't be slow with 10 agents otherwise it will be hard to simulate HPA. In general the current version of GAMA can easily run something like 10k Agent.

However GAMA is not magic if the behavior of your agent is very complex the more agent you have the slower is the simulation.

What I propose is that you explain a bit more what is the behavior of you tourist agent, what are the reflex implemented and what those reflexes are doing. This is a first step to optimize at the behavior level then we can dig in the code and see if some optimization at the code level can be done.

**Comment by agrignard** [comment]
FYI I put an issue on GAMA concerning the Google Maps model there is indeed a problem 

https://github.com/gama-platform/gama/issues/2577

**Comment by agrignard** [comment]
Google API has been updated that's the reason why it doesn't work anymore

 https://cloud.google.com/maps-platform/user-guide/account-changes/#no-plan

So what I propose is that you get the satellite image from QGIS for instance and then use a normal .png as a background

**Comment by agrignard** [comment]
hi @JesusLopezBaeza any update on this issue? let me know if you need any help 

Just to let you know that I am also currently working/Speaking with the GAMA team and we are developing a dedicated pedestrian skills it might be very useful for this project.

**Comment by JesusLopezBaeza** [comment]
Hi @agrignard no news on that yet – I'm still trying to geo-reference a png properly to make it overlap our shapefiles.

Please let me know about the pedestrian skills as soon as they ready ;)

**Comment by agrignard** [comment]
One easy way to georeference an image if you already have the shapefile is using the QGIS plugins called GeoReferencer 
https://docs.qgis.org/2.18/en/docs/user_manual/plugins/plugins_georeferencer.html

**Comment by JesusLopezBaeza** [comment]
Yes, I did that. However to export the image from QGIS as geo-tif, which is not importable by Gama, right?

**Comment by agrignard** [comment]
Yes it does. (I would suggest you to have a detailed look at the model library of Gama to have an overview of what it can do or not)
https://github.com/gama-platform/gama/blob/master/msi.gama.models/models/Features/Data%20Importation/models/GEOTIFF%20File%20Import.gaml

Also you don't have to have a geotiff, what you can do is producing (once its georeferenced) a png image that is aligned with your shapefile then simply using it as a background

**Comment by agrignard** [comment]
any update on this one? Did you find a solution?
